### ISSUE TITLE
Interstitial Not Showing Properly

### ISSUE THREAD

**Issue by ayublin** [tapdaq/unity-plugin#38]
We have managed to show cross promotional interstitial properly in our game, we have tested on several devices and it's showing fine. But we're seeing issue with this device:

- Sony C1905 (Android 4.3)

Here is the correct interstitial being shown in our other device (we're using dummy image):

![image](https://cloud.githubusercontent.com/assets/1355215/23301557/10a5a34c-fabd-11e6-9053-0fd95c2bdeb8.png)

And here is how it looks in the sony device:

![image](https://cloud.githubusercontent.com/assets/1355215/23301568/24260d44-fabd-11e6-8659-243128e9b6ea.png)

It's not only showing as a black blank popup but it will be disappeared by itself in 1 or 2 seconds after being shown.

We're quite bummed to see this issue as we're nearing our release date :( Do you have any suggestion on what we can try to resolve this?

Thanks.

**Comment by rdominic** [comment]
Hi @ayublin 

Sorry to hear about this, the cross promo interstitials will close automatically if the image fails to load, this looks like what happening here. This is likely because the device doesn't have enough memory to load the image to memory. We're looking at ways to improve this.

Can you share any logs with us to confirm this, if they're sensitive please send them to support@tapdaq.com

Added `TLog.setLoggingLevel(TLogLevel.DEBUG);` to your code before Tapdaq is initialised. If you're using Unity, this is set by default.

If this is the case, you will see a log like this `"Not enough memory to load image. %f available. %d required"`

Dominic

**Comment by ayublin** [comment]
Hi @rdominic 

I am using Unity, so the log should be enabled by default right?

![image](https://cloud.githubusercontent.com/assets/1355215/23393327/a79365b0-fdb4-11e6-9a7a-05ca71bfa3e6.png)

If that's the case then I am not seeing the log you mentioned, in the log it shows:

`
_didDisplay INTERSTITIAL
`

Other than that, I don't see any interesting log. Also, as you can see above, we're using the dummy image which should be small in size, and even if the phone isn't a high end one, it has 1GB RAM which I think shouldn't has any problem displaying the interstitial.

**Comment by rdominic** [comment]
Hi @ayublin 

Yeah, you should see all the logs by default, that "Show additional logs" button doesn't do much at the moment, so you should see them all anyway.

We've just released an update and with improvements to image loading, please try it out and let me know how it goes.

Kind Regards,
Dominic

**Comment by ayublin** [comment]
@rdominic nice, I am excited to test this, will let you guys know how it goes, thanks!

**Comment by ayublin** [comment]
Hey @rdominic 

So I have just tried the latest version, it's better now, the black fullscreen popup will be shown, and if I give it sometime, the actual ad will appear.

But I think this can be even better, how about this, let's don't show the popup at all if the ad image hasn't been loaded properly, so do image loading in the background, and show it if it's all done, what do you think?

As with current implementation, it can get quite confusing to the users seeing a black fullscreen popup with a close button, intuitively I will get annoyed and hit the close button immediately.

Thanks!

**Comment by rdominic** [comment]
Sure, that is the longer term plan, but its great to hear that the image is at least loading now.

With this release, images will be cached once loaded (like they are for other NativeAds), so the next time that ad is displayed it will be quicker, but yeah, we will make it so calling loadInterstitial() will load the image before it can be shown. It's in the roadmap and we'll get to it soon.

Dominic

**Comment by ayublin** [comment]
That's good to know. Thanks.

Anyway, how long is it till the cache expired? Yesterday I changed my ad image via dashboard to test the interstitial with larger file instead of gray dummy image. But it's been almost 20 hours and I am still seeing the old ad image.

But this may not be related to the Unity Plugin, since I have tried clearing the app data, but I am still seeing the same old image. Any clue? Or should I send support email?

**Comment by rdominic** [comment]
If the image has changed, then it'll have a new cache based on the new image url, the old one will expire and be removed a few days after its last request. 

Can you send an email to support with your app id/email you've registered with and we'll look further into this.

Thanks,
Dominic

**Comment by PixelEnvision** [comment]
Sure, just sent...

**Comment by PixelEnvision** [comment]
Ah sorry, wrong thread! I thought it was mine :)

**Comment by ayublin** [comment]
@rdominic alright, perfect, email sent, I am closing this issue now. Thanks!

@PixelEnvision haha, no problem, hope everything goes well to you!
